apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: build-push-image-template
  namespace: default
spec:
  params:
    - name: dockerfile-path
      description: dockerfile-path.
    - name: image-url
      description: image-url.
    - name: path-to-context
      description: path-to-context.
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipelinerun-build-push-image-$(uid)
        namespace: default
      spec:
        serviceAccountName: git-serviceaccount
        pipelineRef:
          name: nodejs-pipeline
        resources:
          - name: input-git
            resourceRef:
              name: go-api-skeleton-git
          - name: output-image
            resourceRef:
              name: go-api-skeleton-image
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
        params:
          - name: dockerfile-path
            value: "../Dockerfile"
          - name: image-url
            value: "omarkerdev/tkn-test"
          - name: path-to-context
            value: "workspace/shared-data"
